spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/JwtAuthentication
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: 'update'


logging:
  level:
    org.springframework.security: DEBUG


org:
  springframework:
    security:
      authentication: DEBUG